# Generated by Django 3.1.1 on 2020-09-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '条目'},
        ),
    ]
